# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Fixed development secret to prevent logouts on code changes
# This ensures JWT tokens remain valid across server restarts
development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || 'e8f9a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8' %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || 'test_secret_key_base_fixed_for_testing_purposes_do_not_use_in_production_12345678901234567890123456789012' %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails credentials:edit` to set encrypted secrets.

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

